### PR TITLE
Add support for the "accountId" identifier

### PR DESCRIPTION
**Pull request by choxnox**
Fixed "Pay" function.

### CODE REVIEW

**Comment by angelleye** [comment]
Interesting.  Not sure how I missed that, but thanks for helping out!  I'll get it merged and included in the next update for the library.

**Comment by choxnox** [comment]
I've also fixed the same problem in the "SetPaymentOptions" function.

**Comment by angelleye** [comment]
I still needed to add the AccountID to the $Receiver array in the sample and the templates included with the library, but I merged your changes along with that.  

The dev branch now includes these changes.  The official 2.0.4 release will be soon.

**Comment by NazarenoL** [comment]
This change caused our app to start launching "Undefined index: Account Id" messages. It would have been better to check those variables with `empty()` instead of comparing with `!= ''`

**Comment by angelleye** [comment]
Sorry about that.  I'll take a look and get it resolved with another update here real soon.  In the mean-time, you could revert back if you want to.

**Comment by angelleye** [comment]
@NazarenoL where exactly are you getting that?  I'm not able to reproduce it, and I'm actually a little confused looking at the code based on what you're saying here.  Let me know the line number please.

**Comment by NazarenoL** [comment]
/PayPal/Adaptive.php:351

I replaced:
    $XMLRequest .= $Receiver['AccountID'] != '' ? '<accountId xmlns="">' . $Receiver['AccountID'] . '</accountId>' : '';
with:
    $XMLRequest .= !empty($Receiver['AccountID']) ? '<accountId xmlns="">' . $Receiver['AccountID'] . '</accountId>' : '';

And it's working again for us :)

**Pull request merged**
